### ISSUE TITLE
Ogarnięcie VPS na OVH

### ISSUE THREAD

**Issue by KamilSzerlag** [brewIT2020/brewit-api#14]
Proponuję ubuntu  LTS 18.
https://www.ovh.pl/order/vps/?p1y#/vps/build?selection=~(build~(family~'ssd~quantity~1~osType~'linux~datacenter~'waw~offer~'vps_ssd_model2_2018v1~os~'linux--ubuntu1804-server--64--en))

Na OVH są ceny ok. 

- SSD 
- VPS 2018 SSD
- Czysta instalacja ubuntu 18.04

po 5 zł miesięcznie.

**Comment by KamilSzerlag** [comment]
@suprovsky daj znać w komentarzu na kiedy przewiduszej realizację.

**Comment by suprovsky** [comment]
Zanim cokolwiek kupimy, czy to naprawdę jest wymagane? Jeśli to ma być środowisko dockerowe to możemy postawić takie środowisko na moim VPSie. Co prawda nie mogę do niego dać dostępu, ale do kontenerów owszem.
Jeśli dostęp jest **wymagany**, nie kupujmy VPSa na OVH. Na OVH trzeba będzie VPSa kupić z góry za rok, poza tym VPSy na OVH są droższe niż na innych hostingach, a poza tym możemy wziąć hosting, gdzie mamy opłatę za pół roku. Dla przykładu ja aktualnie korzystam z netcup.de, bo chciałem mieć hosta w Niemczech. Jeśli zgarniemy jakiegoś VPSa w Polsce, prawdopodobnie wyjdzie nam jeszcze taniej, ale netcup już sam w sobie ma bardzo tanie środowisko (dodatkowo mamy lepszy dostęp do maszyny, możemy postawić distro Linuksa jakie chcemy itd/itp):
https://www.netcup.eu/bestellen/produkt.php?produkt=2006

tl;dr zanim wykonamy jakiś zakup chcę mieć pewność, że wszyscy się na to zgadzają

**Comment by KamilSzerlag** [comment]
Radek, proponuję sprawdzić najpierw. :) 
Na ovh można spokojnie wziać serwer na 6, albo na 3 miesiące. 
Do serwera będziemy potrzebować dostęp wszyscy prawdopodobnie, więc ograniczony dostęp absolutnie jest wykluczony.

**Comment by suprovsky** [comment]
temat ogarnięty
