### ISSUE TITLE
Klucze publiczne do SSH

### ISSUE THREAD

**Issue by suprovsky** [brewIT2020/brewit-api#16]
Potrzebuję klucze publiczne do SSH od **każdego** członka projektu.
Ze względu na to, że te repo jest publiczne, proszę byście mi te klucze wysyłali na Discordzie w wiadomości prywatnej. Tag: supra#0337

**Comment by KamilSzerlag** [comment]
@suprovsky @jeik0s  @pazig  @BigSwampToad   Podsyłamy jak będzie stać serwer.

**Comment by suprovsky** [comment]
Temacik gotowy, wszyscy używają kluczy i autoryzacja poprzez hasła jest wyłączona.
