### ISSUE TITLE
#Devops - Przygotowanie środowiska uruchomieniowego dla aplikacji backendowej

### ISSUE THREAD

**Issue by KamilSzerlag** [brewIT2020/brewit-api#7]
Bazy danych.

**Comment by suprovsky** [comment]
Zdecydowaliśmy się tutaj na postawienie wszystkiego w Dockerze, aktualnie to stoi jako usługa systemowa. Przeniesienie się nie powinno zająć długo.
Jak zrobimy plik docker-compose to będziemy mogli zamknąć to.

**Comment by jeik0s** [comment]
ale nam jeszcze brakuje serwisu javowego :P

**Comment by KamilSzerlag** [comment]
Do przeniesienia na repo dockerowe.
